name: Check firmware update for 20 series

on:
  workflow_dispatch:
  schedule:
    - cron: "10 12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        model: [SM-G980F, SM-G981B, SM-G985F, SM-G986B, SM-G988B, SM-N980F, SM-N981B, SM-N985F, SM-N986B]
        region: [DBT, AUT, BTU, ROM]

    steps:
      - name: Check existance of device and firmware
        id: exists
        run: |
          exists=0
          latest=`curl --retry 5 --retry-delay 5 http://fota-cloud-dn.ospserver.net/firmware/${{ matrix.region }}/${{ matrix.model }}/version.xml | grep latest | sed 's/^[^>]*>//' | sed 's/<.*//'`
          [[ -z $latest ]] || exists=1
          echo "exists=$exists" >> $GITHUB_ENV

      - name: Checkout repo
        if: env.exists == 1
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Compare latest version with current version
        if: env.exists == 1
        id: check
        run: |
          need_update=0
          latest=`curl --retry 5 --retry-delay 5 http://fota-cloud-dn.ospserver.net/firmware/${{ matrix.region }}/${{ matrix.model }}/version.xml | grep latest | sed 's/^[^>]*>//' | sed 's/<.*//'`
          latest_short=`echo $latest | cut -d'/' -f1`
          latest_csc=`echo $latest | cut -d'/' -f2`
          latest_modem=`echo $latest | cut -d'/' -f3`
          current=`cat current.${{ matrix.region }}.${{ matrix.model }}` || need_update=1
          [[ $latest != $current ]] && need_update=1
          echo "latest_version=$latest" >> $GITHUB_ENV
          echo "latest_shortversion=$latest_short" >> $GITHUB_ENV
          echo "latest_cscversion=$latest_csc" >> $GITHUB_ENV
          echo "latest_modemversion=$latest_modem" >> $GITHUB_ENV
          echo "need_update=$need_update" >> $GITHUB_ENV

      - name: Update current version
        if: env.need_update == 1
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin ${{github.ref}} --ff-only
          echo ${{ env.latest_version }} > current.${{ matrix.region }}.${{ matrix.model }}
          git add current.${{ matrix.region }}.${{ matrix.model }}
          git commit -m "${{ matrix.model }}/${{ matrix.region }}: ${{ env.latest_version }}"

      - name: Push changes to repo
        if: env.need_update == 1
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
